[workspace]
members = [
    "lib/engine/board",
    "lib/engine/brain",
    "lib/engine/core",
    "lib/game",
    "event-stream",
    "lambda/benchmark",
    "lambda/chessgame",
    "lambda/chessmove",
    "lambda/payloads",
    "openings/dynamodb-uploader",
    "openings/pgn-extractor"
]
exclude = [
    "uci-client"
]