version: "3"
services:
  myopic:
    image: "ghcr.io/th0masb/myopic/event-stream:latest"
    ports:
      - "8080:8080"
    volumes:
      # Mount AWS credentials on host machine into the container
      - ~/.myopic:/root/.aws:ro
    environment:
      # Pull auth token from the host environment
      LICHESS_AUTH_TOKEN: "${MYOPIC_LICHESS_AUTH_TOKEN}"
      RUST_BACKTRACE: "1"
      # Configure the bot parameters
      APP_CONFIG: >-
        {
          "gameFunction": {
            "id": { "name": "LichessGameLambda" },
            "abortAfterSecs": 30
          },
          "moveFunction": {
            "name": "Myopic-Move"
          },
          "lichessBot": {
            "botId": "myopic-bot"
          }
        }
  hyperopic:
    image: "ghcr.io/th0masb/myopic/event-stream:latest"
    ports:
      - "8081:8080"
    volumes:
      # Mount AWS credentials on host machine into the container
      - ~/.myopic:/root/.aws:ro
    environment:
      # Pull auth token from the host environment
      LICHESS_AUTH_TOKEN: "${HYPEROPIC_LICHESS_AUTH_TOKEN}"
      RUST_BACKTRACE: "1"
      # Configure the bot parameters
      APP_CONFIG: >-
        {
          "gameFunction": {
            "id": { "name": "LichessGameLambda" },
            "abortAfterSecs": 30
          },
          "moveFunction": {
            "name": "Hyperopic-Move"
          },
          "lichessBot": {
            "botId": "Hyperopic"
          },
          "userMatchers": [
            {
              "include": true,
              "pattern": "^th0masb$$"
            }
          ]
        }
