name: Pull request checks
on:
  pull_request:
    branches:
      - master
jobs:
  compile_and_test:
    name: Compile and test
    runs-on: ubuntu-20.04
    container:
      image: rust:1.69-bullseye
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --release
  cross_build_event_stream:
    name: Cross build event-stream application
    runs-on: ubuntu-20.04
    env:
      APP_NAME: "event-stream"
      TARGETS: "aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu"
      DOCKERFILE: "tools/event-stream.dockerfile"
      DRYRUN: "1"
    steps:
      - uses: actions/checkout@v2
      - run: ./tools/setup-cross-deps.sh
      - run: VERSION="$GITHUB_SHA" ./tools/publish-multi-platform.sh
