name: Pull request checks
on:
  pull_request:
    branches:
      - master
jobs:
  compile_and_test:
    name: Compile and test
    runs-on: ubuntu-20.04
    container:
      image: rust:1.69-bullseye
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --release
