name: Publish event-stream
on:
  push:
    branches:
      - ISSUE-131
        #  paths:
        #    - event-stream/**
jobs:
  publish-event-stream:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install rustup
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
      - name: Print rustup version
        run: rustup --version
      - name: Install cross
        run: cargo install cross
      - name: Echo pwd
        run: pwd
      - name: Build event-stream
        run: cross build --manifest-path=event-stream/Cargo.toml --target=aarch64-unknown-linux-musl

