name: Publish event-stream
on:
  push:
    branches:
      - master
    paths:
      - event-stream/**
      - tools/**
jobs:
  publish-event-stream:
    runs-on: ubuntu-20.04
    env:
      APPLICATION_DIR: "event-stream"
      TARGETS: "aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu"
      DOCKERFILE: "tools/Dockerfile.debian"
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ./tools/setup-cross-deps.sh
      - run: VERSION="$GITHUB_SHA" ./tools/publish-multi-platform.sh
